# Generated by Django 5.2.7 on 2025-10-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=120, null=True)),
                ('referrer_wallet', models.CharField(blank=True, max_length=120, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
